# Generated by Django 6.0 on 2025-12-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='innovation_proofs/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovations', to='faculty.faculty')),
            ],
        ),
    ]
