# Generated by Django 6.0 on 2025-12-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationcontribution',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='innovation_proofs/'),
        ),
    ]
